/*
 * @Author: your name
 * @Date: 2021-12-10 21:14:55
 * @LastEditTime: 2021-12-10 21:49:34
 * @LastEditors: Please set LastEditors
 * @Description: 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 * @FilePath: \console-next\components\layout.tsx
 */

import React from "react";
import Head from 'next/head'
import styles from "../styles/Home.module.css";
import Footer from "./footer";
import Header from "./header";
interface LayoutProps {
  title?: string
}
const Layout: React.FC<LayoutProps> = (porps) => (
  <>
    <Head>
      <title>{porps.title || 'Popochiu'}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.container}>
      <Header />
      <main className={styles.main}>
        {
          porps.children
        }
      </main>

      <Footer />
    </div>

  </>
);
export default Layout;
